spring.datasource.url=jdbc:postgresql://ep-dawn-hat-aqtb1jzg.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vIX7OKlbczq8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8098
spring.h2.console.enabled=false
spring.mvc.format.date=yyyy-MM-dd